SELECT 
	   [track_name] as [Nazwa utworu]
      ,[artist_name] as [Artysta]
      ,[artist_count] as [L. Artystow]
      ,[released_year] as [Rok wydania]
      ,[released_month] as [Miesiac wydania]
      ,[released_day] as [Dzien wydania]
      ,[in_spotify_playlists] as [W ilu playlistach]
    --  ,[in_spotify_charts]
      ,[streamsmln] as [L. odtworzen]
   --   ,[in_apple_playlists]
  --    ,[in_apple_charts]
     -- ,[in_deezer_playlists]
    --  ,[in_deezer_charts]
      --,[in_shazam_charts]
      ,[bpm] 
     -- ,[klucz]
     -- ,[mode]
      --,[danceability]
      --,[valenc]
      --,[energy]
      --,[acousticness]
      --,[instrumentalness]
     -- ,[liveness]
    --  ,[speechiness]
  FROM DUZE
  order by [L. odtworzen] desc
